### ISSUE TITLE
Shiro.ini

### ISSUE THREAD

**Issue by samchorlton** [unchartedsoftware/TellFinder#2]
In the web.xml file (/var/lib/tomcat7/webapps/tellfinder/WEB-INF/web.xml) there is a configuration setting: 

<context-param>
                <param-name>shiroConfigLocations</param-name>
                <param-value>file:/etc/tellfinder/shiro.ini</param-value>
        </context-param>

This file does not exist as part of the src package. Is this file meant to be created? and if so what are the contents meant to be?

It is currently causing a JAVA file not found exception in the catalina logs. 

Thanks

**Comment by chris-dickson** [comment]
Hey Sam, 

I've created an /auth directory that should contain all the files you need to get authentication set up.  There is a README.md in there that describes the steps you'll need to take.

-Chris
