### ISSUE TITLE
/tellfinder not found

### ISSUE THREAD

**Issue by mikew77** [unchartedsoftware/TellFinder#3]
Hi folks, just built two environments attempting to get tellfinder deployed.  I followed the basic instructions on the website but somehow got the same error both times.

The war seems to build ok and tomcat installs ok.  I can hit localhost:8080 and getting a response from tomcat base, but when I hit localhost:8080/tellfinder I get the following 404.  I've checked tomcat's logs but can't see anything that looks amiss.  A bit broad I'm afraid but was wondering if you had any hints or suggestions?

Environment is ubuntu 14.04 running with open JDK 7 and Tomcat 7.0.69

Thanks for any advice you can offer!

"HTTP Status 404 - /tellfinder

type Status report

message /tellfinder

description The requested resource is not available."

**Comment by mikew77** [comment]
I checked my Catalina.out log file and found some severe errors:

May 02, 2016 3:30:12 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log fil
e
May 02, 2016 3:30:12 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/tellfinder] startup failed due to previous errors
May 02, 2016 3:30:12 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/tellfinder] appears to have started a thread named [MySQL Statement Cancellation
 Timer] but has failed to stop it. This is very likely to create a memory leak.
May 02, 2016 3:30:13 AM org.apache.catalina.startup.HostConfig deployWAR

Can anyone tell me where I can find the appropriate container log file?  If listeners aren't starting, it seems like a good place for me to start investigating...

**Comment by chris-dickson** [comment]
Have you edited the shiro.ini so that it is able to connect to the database for authentication?  Specifically the following four lines:

```
ds.serverName = DATABASE_HOST
ds.user = DATABASE_USER
ds.password = DATABASE_PASSWORD
ds.databaseName = DATABASE_UNCHARTED_SCHEMA
```

**Comment by mikew77** [comment]
I think so; the only piece I wasn't sure about was line four - which database should that be? In my instance I have that set to roxy_ui as that's where I created the users and roles tables.

**Comment by chris-dickson** [comment]
We usually store it in the other schema.  I can't think of a reason why it wouldn't work.

Does everything get initialized successfully in the `contextInitialized` function in `DBInitListener.java`.  That's usually one of the first places where connection problems will show up.

**Comment by mikew77** [comment]
I'll check now; should I look in catalina.out for that?

**Comment by mikew77** [comment]
Just wondering if the password and username are getting passed through for authentication ok...

[ERROR] 02 May 2016 16:08:51 - org.apache.shiro.realm.jdbc.JdbcRealm - There was a SQL error while authenticatin
g user [jsmith]
java.sql.SQLException: Access denied for user ''@'localhost' (using password: NO)

Looking at the error message it's got the user "jsmith" but says "password: NO".

Where do you normally store the user and roles tables?  memex_unchartered ?

**Comment by mikew77** [comment]
Ok; so I moved the user and roles info to the memexo_unchartered table and updated my shiro.ini file as follows.
# Connection
ds = oculus.memex.shiro.EnvMysqlDataSource
ds.serverName = localhost
ds.user = root
ds.password = admin
ds.databaseName = memex_uncharted

I then restarted tomcat and tried to log in; no effect.  Same errors - but when I checked further up in catalina.log I did see a DBInitListener issue as pasted below.  Not sure if they're red herrings, but messages about jdbc deregistering and potential memory leaks...Any ideas?

May 02, 2016 4:23:28 PM org.apache.catalina.core.StandardServer await
INFO: A valid shutdown command was received via the shutdown port. Stopping the Server instance.
May 02, 2016 4:23:28 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-bio-8080"]
May 02, 2016 4:23:28 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["ajp-bio-8009"]
May 02, 2016 4:23:28 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Catalina
[INFO] 02 May 2016 16:23:28 - oculus.memex.init.DBInitListener - deregistering jdbc driver: com.mysql.jdbc.Drive
r@206b00cb
[INFO] 02 May 2016 16:23:28 - oculus.memex.init.DBInitListener - MySQL connection cleanup thread shutdown
[INFO] 02 May 2016 16:23:28 - oculus.memex.init.DBInitListener - MySQL connection cleanup thread shutdown succes
sful
[INFO] 02 May 2016 16:23:28 - org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Disabled session v
alidation scheduler.
May 02, 2016 4:23:28 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/tellfinder] appears to have started a thread named [MySQL Statement Cancellation T
imer] but has failed to stop it. This is very likely to create a memory leak.
May 02, 2016 4:23:28 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-bio-8080"]

**Comment by chris-dickson** [comment]
Still looking into this.  I'm trying to get it running on Ubuntu 14.04 and seeing the same issue.  Will update when fixed.

**Comment by mikew77** [comment]
Thanks Chris; was just thinking this morning of trying a Windows deployment for now. Maybe will try a win7 rollout unless you suggest otherwise.

**Comment by chris-dickson** [comment]
Just pushed a fix for it.  Verified working on Ubuntu 14.04.  

Let me know if this fixes it for you as well.

**Comment by mikew77** [comment]
Great thanks I'll give it a go hopefully today and will let you know.

**Comment by mikew77** [comment]
Good news, it deployed and I can now log in.  Although the download of
initial data results get stuck in a busy loop - did this work for you
earlier?  Can't see any issues in the log files, but will keep looking.

**Comment by mikew77** [comment]
This seems to be authenticating ok now.  Have other issues with ads table in roxy_ui, will open under separate issue.  Thanks for your help.
