### ISSUE TITLE
'roxy_ui.ads' does not exist

### ISSUE THREAD

**Issue by mikew77** [unchartedsoftware/TellFinder#4]
When running "ant -buildfile process.xml", I get the following error:

 [java] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'roxy_ui.ads' doesn't exist

It repeats a number of times as attached in the file "ant_build_issues.txt".

I tried to reload the sample.sql file into mysql and got the corresponding errors - of particular concerns seems to be roxy_ui.ads which doesn't seem to be created unlike the other tables when absent or ignored if duplicate:

Database changed
ERROR 1050 (42S01): Table 'sources' already exists
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
ERROR 1293 (HY000): Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in
 DEFAULT or ON UPDATE clause
ERROR 1146 (42S02): Table 'roxy_ui.ads' doesn't exist
ERROR 1050 (42S01): Table 'ads_attributes' already exists
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
ERROR 1293 (HY000): Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in
 DEFAULT or ON UPDATE clause
[ant_build_issues.txt](https://github.com/unchartedsoftware/TellFinder/files/255364/ant_build_issues.txt)

**Comment by mikew77** [comment]
OS is Ubuntu 14.04.  Version info from mysql is attached:

mysql> show variables like "%version%"
    -> ;
+-------------------------+-------------------------+
| Variable_name           | Value                   |
+-------------------------+-------------------------+
| innodb_version          | 5.5.49                  |
| protocol_version        | 10                      |
| slave_type_conversions  |                         |
| version                 | 5.5.49-0ubuntu0.14.04.1 |
| version_comment         | (Ubuntu)                |
| version_compile_machine | x86_64                  |
| version_compile_os      | debian-linux-gnu        |
+-------------------------+-------------------------+
7 rows in set (0.00 sec)

**Comment by mikew77** [comment]
Sorry about the message storm ... but I tried to copy and paste the "CREATE TABLE 'ads'..." sql from the sample.sql file on the command line and got the following error message complaining about multiple fields having the current timestamp value:

ERROR 1293 (HY000): Incorrect table definition; there can be only one TIMESTAMP column with CURRENT
_TIMESTAMP in DEFAULT or ON UPDATE clause

Looks like importtime and modtime may be the fields in question...unless this is a red herring....

**Comment by chris-dickson** [comment]
Your MySQL version needs to be 5.6.

**Comment by mikew77** [comment]
ah great, I'll give that a go now - thanks!

**Comment by mikew77** [comment]
That worked; thanks Chris.  Is there any documentation on how to get scraping working?  I have sample data showing up but would like to be able to direct tellfinder to a set of sites or pages to monitor.

**Comment by chris-dickson** [comment]
Tellfinder is just set up to view the data. Scraping is on you. :)

**Comment by mikew77** [comment]
Gotcha!  So I'd need to somehow get my scraping to output to the mysql database and can use Tellfinder to explore from there.  Thanks for your help in getting Tellfinder up and running; gotta spend some time working this out from here!
